version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - github_actions
  # maintain dependencies for python project
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - dependencies
    allow:
      # Allow updates for react and related packages
      - dependency-name: "react*"
      - dependency-name: "web-vitals"
      # common for all project
      - dependency-name: "superagent"
      - dependency-name: "process"
      # serve the static site
      - dependency-name: "serve"
